23-6-RealMySQL:
  members:
  - github: dojinyou
  - github: choihuk
  - github: sectionr0
  - github: tlarbals824
  - github: 5uhwann
  - github: Youngcircle-kim
  - github: JEONG-JIHWAN
  
23-7-SystemDesignInterview:
  members:
  - github: dojinyou
  - github: sectionr0
  
23-8-SpringBoot:
  members:
  - github: dojinyou
  - github: 5uhwann
  - github: jungyeons
  
23-9-Algorithm:
  members:
  - github: dojinyou
  - github: 5uhwann
  - github: jungyeons
