name: 'Team Sync'
on: workflow_dispatch

jobs:
  synchronize-teams:
    runs-on: ubuntu-latest
    steps:
    - uses: rmacklin/team-sync@v0
      with:
        repo-token: "${{ secrets.GH_TOKEN }}"
        team-data-path: 'teams.yaml'
