name: Update members

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'members.yaml'

jobs:
  update-members:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - uses: codingpot/github-org-member-manage-action@v1
        with:
          gh_token: ${{ secrets.GITH_TOKEN }}
          members_filepath: members.yaml
          mode: sync
